import type { Metadata } from "next";
import { PT_Serif } from "next/font/google";
import "./globals.css";
import { GlobalProvider } from "./context/global-provider";

const serif = PT_Serif({
  subsets: ["latin"],
  weight: ["400", "700"],
});
export const metadata: Metadata = {
  title: "Mini Social",
  description: "Generated by create next app",
  icons:{
    icon: "/vercel.svg",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body className={`${serif.className} h-[100vh]`}>
        <GlobalProvider>
        {children}
        </GlobalProvider>
      </body>
    </html>
  );
}
